#!/bin/bash

API_KEY_ID_FALCON=API_KEY_ID_HERE
API_KEY_SECRET_FALCON=API_KEY_SECRET_HERE
API_KEY_KANDJI=API_KEY_HERE 
export INTUNE_CLIENT_ID=""ENTER_ID_HERE""
export INTUNE_CLIENT_SECRET="ENTER_SECRET_HERE"
export INTUNE_TOKEN_URL="ENTER_TOKEN_URL_HERE"
